// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhDdaE9tnQeUPIQp4aE7U5zj6SiFVeaw',
    appId: '1:443391482789:android:fe1fc1a0bbc02fc925e64c',
    messagingSenderId: '443391482789',
    projectId: 'realtime-tracking-location',
    databaseURL: 'https://realtime-tracking-location-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-tracking-location.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsfUtb2x2uFwetFe0iDA6teM1BO47Av0E',
    appId: '1:443391482789:ios:c0ef18c6185a48c425e64c',
    messagingSenderId: '443391482789',
    projectId: 'realtime-tracking-location',
    databaseURL: 'https://realtime-tracking-location-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-tracking-location.firebasestorage.app',
    iosBundleId: 'com.pixel.baseapp',
  );
}
